In [2]:
# Tensor 的连接
import torch
a = torch.ones(3, 3)
b = 2 * torch.ones(3, 3)
print(a)
print(b)
c = torch.cat((a, b), dim=1)
print(c)

c = torch.cat((a, b), dim=0)
print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [3]:
# 增加维度 stack
c = torch.stack((a, b), dim=0)
print(c)

c = torch.stack((a, b), dim=1)
print(c)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]])
tensor([[[1., 1., 1.],
         [2., 2., 2.]],

        [[1., 1., 1.],
         [2., 2., 2.]],

        [[1., 1., 1.],
         [2., 2., 2.]]])


In [4]:
# Tensor 切分 chunk

# 32 channels
input = torch.randn(32, 64, 64)
# split into 8 chunks along channel dimension
chunks = torch.chunk(input, 8, dim=0)
for i, chunk in enumerate(chunks):
    print(f"Chunk {i} shape: {chunk.shape}")

Chunk 0 shape: torch.Size([4, 64, 64])
Chunk 1 shape: torch.Size([4, 64, 64])
Chunk 2 shape: torch.Size([4, 64, 64])
Chunk 3 shape: torch.Size([4, 64, 64])
Chunk 4 shape: torch.Size([4, 64, 64])
Chunk 5 shape: torch.Size([4, 64, 64])
Chunk 6 shape: torch.Size([4, 64, 64])
Chunk 7 shape: torch.Size([4, 64, 64])


In [5]:
A=torch.tensor([1,2,3,4,5,6,7,8,9,10])
# 不等量切分
B = torch.chunk(A, 3, 0)
for i, b in enumerate(B):
    print(f"Chunk {i}: {b}")

# 长度分别是 4，4，2 位。这是怎么分的呢，不应该是 3，3，4 这样更为平均的方式么？
# chunk 函数是先做除法，然后再向上取整得到每组的数量（注意是向上取整）

# 那如果 chunk 参数大于 Tensor 可以切分的长度，就会把被切分的 Tensor 只能分成若干个长度为 1 的向量

Chunk 0: tensor([1, 2, 3, 4])
Chunk 1: tensor([5, 6, 7, 8])
Chunk 2: tensor([ 9, 10])


In [6]:
# chunk 函数，是按照“切分成确定的份数”来进行切分的，那如果想按照“每份按照确定的大小”来进行切分
# 可以使用 torch.split 函数

A=torch.rand(4,4)
# split size_or_sections 可以是一个整数，表示每一份的大小
B = torch.split(A, 2, dim=0)
for i, b in enumerate(B):
    print(f"Split {i}: {b}")


A=torch.rand(5,4)
# split_size_or_sections 可以是一个列表，表示每一份的大小
B=torch.split(A,(2,2,1),0)
for i, b in enumerate(B):
    print(f"Split {i}: {b}")


Split 0: tensor([[0.5663, 0.6546, 0.4672, 0.8208],
        [0.9446, 0.2627, 0.3186, 0.3258]])
Split 1: tensor([[0.6373, 0.4146, 0.5292, 0.9575],
        [0.4755, 0.1363, 0.9701, 0.1527]])
Split 0: tensor([[0.8965, 0.9684, 0.7533, 0.8419],
        [0.8409, 0.1131, 0.0438, 0.3762]])
Split 1: tensor([[0.3917, 0.3818, 0.5565, 0.8991],
        [0.1206, 0.9700, 0.0465, 0.3075]])
Split 2: tensor([[0.1655, 0.3694, 0.8687, 0.8399]])


In [7]:
# unbind 函数：沿指定维度移除张量的一个维度，并返回一个元组，包含所有切片后的张量
A = torch.randn(3, 4, 5)
B = torch.unbind(A, dim=1)
# if dim is 1 means unbind along the second dimension
for i, b in enumerate(B):
    print(f"Unbind {i}: {b}")

# unbind 是一种降维切分的方式，相当于删除一个维度之后的结果。

Unbind 0: tensor([[-1.2208, -0.2413,  1.6901, -0.5783, -1.6049],
        [ 0.8374,  0.9689, -0.0543, -0.3896, -0.0918],
        [ 0.6151, -0.3588, -1.9207,  2.6521, -0.8539]])
Unbind 1: tensor([[-0.4769, -0.7594, -0.5618,  0.4039,  0.4695],
        [-2.1413, -1.5147,  0.1714,  0.7763,  0.9834],
        [-0.4921,  0.3430, -0.8709, -0.5011,  1.5466]])
Unbind 2: tensor([[-1.1893, -1.4522, -0.8917,  1.0523,  1.0498],
        [-2.2550, -2.0617,  1.4712,  0.1001,  0.2586],
        [ 1.0543, -0.4837,  1.2428, -0.1238, -0.2266]])
Unbind 3: tensor([[ 1.6378,  0.8954,  0.6025, -0.4242, -0.2850],
        [ 1.0454,  0.4556,  1.1422, -0.1685,  0.0769],
        [ 1.0211, -0.8556, -0.8372, -0.7319,  0.6541]])


In [8]:
# Tensor 的索引操作
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[0, 0])  # 输出: tensor(1)
print(a[:, 1])  # 输出: tensor([2, 5, 8])
print(a[1, :])  # 输出: tensor([4, 5, 6])

# index_select
A=torch.arange(0,16).view(4,4)
print(A)
B=torch.index_select(A,0,torch.tensor([1,3]))
C=torch.index_select(A,1,torch.tensor([0,3]))
print(B)
print(C)

# 从第 0 维选择第 1（行）和 3（行）的数据，并得到了最终的 Tensor B，其大小为 2x4。
# Tensor A 中选择第 0（列）和 3（列）的数据，得到了最终的 Tensor C，其大小为 4x2。

tensor(1)
tensor([2, 5, 8])
tensor([4, 5, 6])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[ 4,  5,  6,  7],
        [12, 13, 14, 15]])
tensor([[ 0,  3],
        [ 4,  7],
        [ 8, 11],
        [12, 15]])


In [9]:
# masked_select
# 通过一些判断条件来进行选择，比如提取深度学习网络中某一层中数值大于 0 的参数。
A = torch.randn(4, 4)
B = torch.masked_select(A, A > 0.3,out=None)
print(A)    
print(B)

tensor([[-0.4882,  1.0881,  0.1695,  0.8314],
        [ 0.8505,  0.0342, -0.7567,  0.0437],
        [-0.0247,  0.3069,  1.8622,  0.6370],
        [ 0.2714,  0.0234, -0.0063, -1.7876]])
tensor([1.0881, 0.8314, 0.8505, 0.3069, 1.8622, 0.6370])


# 常用汇总

![mdfiles/image3.png](mdfiles/image3.png)


index_select 返回的结果和输入是一个维度，而masked_select返回一维输出
stack和cat的一个不同点在于，stack会升维，而cat不会。
split获取的是原输入的视图，也就是对split的结果的操作会影响原来的数据


In [15]:
A=torch.tensor([[4,5,7], [3,9,8],[2,3,4]])

print(A)


mask = torch.tensor([[1,0,0], [1,1,0],[0,0,1]], dtype=torch.bool)
selected = torch.masked_select(A, mask>0)
print(selected)  # 输出: tensor([4, 9, 4])

tensor([[4, 5, 7],
        [3, 9, 8],
        [2, 3, 4]])
tensor([4, 3, 9, 4])
